### ISSUE TITLE
Add checklist for PR requests

### ISSUE THREAD

**Issue by jason-ransom-slalom** [ToyotaResearchInstitute/lakefront#253]
In order to better prevent creating new components without performing all of the contribution steps, it would be good to add a pull request checklist to the repo. [This Article](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) explains more about it.

An example could be something like this:

## Lakefront PR Checklist

- [ ] Exported any new components in the src/index.ts
- [ ] #255
- [ ] Ensured version numbers bumped properly.
- [ ] Removed any irrelevant commit messages from merge commit.
- [ ] Deleted branch after merge.
